@startuml
activate TestCase
activate Jugador
activate Pregunta
activate Seleccion
activate RespuestaIncorrecta
activate RespuestaCorrecta
activate List

TestCase -> Jugador: new Jugador()
Jugador -> TestCase:  Jugador
TestCase -> RespuestaIncorrecta: new RespuestaIncorrecta
RespuestaIncorrecta --> TestCase: respuestaJugador1
TestCase -> RespuestaCorrecta: new RespuestaCorrecta
RespuestaCorrecta --> TestCase: respuestaJugador2
TestCase ->Pregunta: new Pregunta()
TestCase -> List : new List()
List --> TestCase: listaDeRespuestas
TestCase -> Pregunta: clasificarRespuesta(listaDeRespuestas)
Pregunta -> Seleccion: Calificar()
Seleccion->Respuesta : calificar()
Respuesta --> Seleccion: calificacion
Seleccion ->  Jugador : modificarPuntaje(calificacion)






deactivate TestCase
deactivate Jugador
deactivate Seleccion
deactivate Pregunta
deactivate RespuestaIncorrecta
deactivate RespuestaCorrecta
@enduml