@startuml
Panel -> Pregunta ++ : calificar(selecciones)
loop : por cada seleccion
Pregunta -> Seleccion ++ : calificarNormal()
Seleccion -> Respuesta ++ : calificar()
return puntos
Seleccion -> Jugador ++ : sumarPuntaje(puntos)

deactivate Jugador
deactivate Seleccion
deactivate Pregunta
end
@enduml