@startuml
hide circle
skinparam classAttributeIconSize 0

'Clases
class Panel{
    +cargarPregunta(): Void
    +enviarRespuesta(): Void
    -monstrarOpciones(): Void
    -mostrarEnunciado(): Void
}


Abstract Pregunta{
    -enunciado():String
    -respuestasCorrectas():List<Respuesta>
    -respuestasIncorrectas():List<Respuesta>
    +obtenerOpciones(): List<Respuesta>
    +calificar(Seleccion seleccion):int
}

Abstract Respuesta{
    -nombre:string
    +nombre():String
    +calificar(Abstracto): Void
    +igual(respuesta:Respuesta): Boolean
    +esCorrecta(Abstracto):boolean
}

Class RespuestaCorrecta{
    +RespuestaCorrecta(nombre:String)
    +calificar():int
    +esCorrecta():boolean
}

Class RespuestaIncorrecta{
   +RespuestaIncorrecta(nombre:String)
    +calificar():int
    +esCorrecta():boolean
}

Class PreguntaVoF{
   +PreguntaVoF(enunciado:String,respuestaCorrecta:RespuestaCorrecta,respuestaIncorrecta:RespuestaIncorrecta)
   +PreguntaVoF(enunciado:String,respuestaIncorrecta:RespuestaIncorrecta,respuestaCorrecta:RespuestaCorrecta)
}



Class PreguntaChoise{
    +agregar(respuesta:RespuestaCorrecta):void
    +agregar(respuesta:RespuestaIncorrecta):void

}




Class PreguntaGroup{
    +calificar(Selecciones):int
}



Class Seleccion{
    -jugador:Jugador
    -misRespuestasCorrestas:List<Respuesta>
    -misRespuestasIncorrestas:List<Respuesta>
    -busteador
    +Selecion(jugador:Jugador)
    +agregar(respuesta:RespuestaCorrecta)
    +agregar(respuesta:RespuestaIncrrecta)
    +calificarNormal()
    +calificarParcial()
    +calificarChoice()
}

Class Jugador{
    -nombre:String
    -puntos:int
    +Jugador(nombre:String)
    + modificarPuntaje(numero:int):void
    +obtenerPuntaje():int
}

Abstract Ronda{
   -pregunta: Pregunta
   -selecciones:List<Seleccion>
   +agregarSeleccion(Seleccion seleccion):void
   +abstract clasificar():void
   +aplicarBusteador()
}

'Relaciones
Pregunta -right-* "*" Respuesta
RespuestaIncorrecta -down-|> Respuesta
RespuestaCorrecta -down-|> Respuesta
PreguntaVoF -up-|> Pregunta
PreguntaChoise -up-|> Pregunta
PreguntaGroup -left-|> Pregunta
Pregunta ..up.>Ronda
Ronda -left-* "*" Seleccion
RondaClasica -down-|>Ronda
RondaParcial -down-|>Ronda
RondaPenalizada -down-|>Ronda
Ronda -left-> Jugador

@enduml