@startuml
PanelDeControl ->RondaClasica:RondaClasica(Pregunta)
loop Por Cada Selecion
PanelDeControl -> RondaClasica:agregar(Selecion)
end
PanelDeControl -> RondaClasica:calificar()
loop Por Cada Selecion
RondaClasica -> PreguntaChoice : obteneRespuestasCorrectas
PreguntaChoice --> RondaClasica: respuestasCorrectas
RondaClasica -> Selecion : calificar(respuestasCorrectas)
Selecion ->Jugador : modificarPuntaje (int valor)
end


@enduml