@startuml
skinparam classAttributeIconSize 0
hide footbox
Participant User
activate User
User -> Pregunta ++: calificar(respuestas)
loop Cada respuesta
Participant Respuesta as "respuesta: Respuesta"
Pregunta -> Respuesta ++: getOpciones()
return opcionesElegidas
Participant Calificador as "calificador: VerificadorDecorator"
Pregunta -> Calificador ++: calificar(opcionesCorrectas, opcionesElegidas)
Calificador -> Verificador ++:

end


@enduml