@startuml
hide circle
skinparam classAttributeIconSize 0

'Clases
Class Panel{
 }

Class Pregunta{

}

Class Respuesta{

}

Class PreguntaVoF{

}

Class PreguntaMultipleChoise{

}

Class GroupChoice{

}

Class TipoMChoise{

}

Class ClasicMChoice
Class ParcialMChoice
Class OrdererChoice

Class Seleccion{

}

Class Jugador{

}

Class Puntaje{
}


Class Exclusividad
Class Multiplicador

'Relaciones

Panel --* "*" Pregunta
Pregunta -left-* "*" Respuesta
RespuestaIncorrecta -up-|> Respuesta
RespuestaCorrecta -up-|> Respuesta
PreguntaVoF -up-|> Pregunta
PreguntaMultipleChoise -up-|> Pregunta
GroupChoice -up-|> Pregunta
PreguntaMultipleChoise -down-> TipoMChoise
ClasicMChoice -up-|> TipoMChoise
ParcialMChoice -up-|> TipoMChoise
OrdererChoice -up-|> TipoMChoise
Pregunta .left.> Seleccion
Seleccion -up-> Jugador
Jugador -right-> Exclusividad
Jugador -right-> Multiplicador

@enduml