@startuml
hide circle
skinparam classAttributeIconSize 0

'Clases
Interface Respuesta{
    +{abstract}calificar(): int
    +{abstract}esCorrecta(): boolean
}

Class RespuestaCorrecta{
    +calificar(): int
    +esCorrecta(): boolean
}

Class RespuestaIncorrecta{
    +calificar(): int
    +esCorrecta(): boolean
}

Class RespuestaIncorrectaPenalizada{
    +calificar(): int
    +esCorrecta(): boolean
}

Abstract Class Pregunta{
    -enunciado: String
    +{abstract}{static}Pregunta(enunciado: String)
    +asignarRespuestaCorrecta(respuestaCorrecta: String): void
    +esCorrecta(respuesta: String): boolean
    +calificar(selecciones: List<Seleccion>): void
}

Class PreguntaVoFClasico{
   +{static}PreguntaVoFClasico(enunciado: String)
}

Class PreguntaVoFPenalizado{
   +{static}PreguntaVoFPenalizado(enunciado: String)
}

Class Seleccion{
    -respuesta: String
    +{static}Seleccion(jugador: Jugador, respuesta: String)
    +calificar(respuestas: HashMap<String, Respuesta>): void
}

Class Jugador{
    -nombre: String
    -puntos: int
    +{Static}Jugador(nombre: String)
    +modificarPuntaje(numero:int): void
    +obtenerPuntaje(): int
}

'Relaciones
RespuestaIncorrecta ..|> Respuesta
RespuestaIncorrectaPenalizada ..|> Respuesta
RespuestaCorrecta ..|> Respuesta
PreguntaVoFPenalizado --|> Pregunta
PreguntaVoFClasico --|> Pregunta
Seleccion o-- Jugador
Pregunta "1" *-left- "*" Respuesta
Seleccion .up.> Respuesta

@enduml