@startuml
hide circle
skinparam classAttributeIconSize 0

'Clases
Interface Opcion{
    +{abstract}calificar(): int
    +{abstract}esCorrecta(): boolean
}

Class OpcionCorrecta{
    +calificar(): int
    +esCorrecta(): boolean
}

Class OpcionIncorrecta{
    +calificar(): int
    +esCorrecta(): boolean
}

Class OpcionIncorrectaPenalizada{
    +calificar(): int
    +esCorrecta(): boolean
}

Abstract Class Pregunta{
    -enunciado: String
    +{abstract}{static}Pregunta(enunciado: String)
    +asignarOpcionCorrecta(opcionCorrecta: String): void
    +esCorrecta(Opcion: String): boolean
    +calificar(Respuestaes: List<Respuesta>): void
}

Class PreguntaVoFClasico{
   +{static}PreguntaVoFClasico(enunciado: String)
}

Class PreguntaVoFPenalizado{
   +{static}PreguntaVoFPenalizado(enunciado: String)
}

Class Respuesta{
    -opcionElegida: String
    +{static}Respuesta(jugador: Jugador, opcionElegida: String)
    +calificar(opciones: HashMap<String, Opcion>): void
}

Class Jugador{
    -nombre: String
    -puntos: int
    +{Static}Jugador(nombre: String)
    +modificarPuntaje(numero:int): void
    +obtenerPuntaje(): int
}

'Relaciones
OpcionIncorrecta ..|> Opcion
OpcionIncorrectaPenalizada ..|> Opcion
OpcionCorrecta ..|> Opcion
PreguntaVoFPenalizado --|> Pregunta
PreguntaVoFClasico --|> Pregunta
Respuesta o-- Jugador
Pregunta "1" *-left- "*" Opcion
Respuesta .up.> Opcion

@enduml