@startuml
loop PorCadaRspuestaConOrden
PanelDeControl-> RespuestaConOrden:new RespuestaConOrden(posicion:int)
end
PanelDeControl -> OrderedChoise:new OrderedChoise(enunciado)
loop PorCadaRespuestaConOrden
PanelDeControl -> OrderedChoise: agregar(RespuestaConOrden)
end
PanelDeControl ->OrderedChoise: obtenerOpciones()
loop porJugador
PanelDeControl-> Seleccion: new Seleccion(Jugador)
end
loop porCadaSeleccion
PanelDeControl -> Seleccion: proponer(RespuestaConOrden, posicionPropuesta)
Seleccion -> Seleccion: new RespuestaConOrden(RespuestaConOrden,posicionPropuesta)
end
PanelDeControl -> Ronda: new Ronda()
loop porCadaSeleccion
PanelDeControl ->Ronda: agregar(Selecion)
end
PanelDeControl -> Ronda : calificar()
loop PorCadaSelecion
Ronda -> Seleccion: calificarOrden()
Seleccion -> RespuestaConOrden: calificarOrden()
RespuestaConOrden --> Seleccion: valor
Seleccion -> Jugador: moficarPuntaje(valor)
end
@enduml