@startuml

PanelControl ->RondaParcial: new RondaParcial(Pregunta)
    loop  PorCadaSelecion
    PanelControl -> RondaParcial:  agregar(selecion)
    end
PanelControl ->RondaParcial: calificar()
    loop PorCadaSelecion
RondaParcial -> Selecion: calificarParcial()
    loop PorCadaRespuestaCorrectaSiNoTengoRespuestasIncorrectas
    Selecion -> RespuestaCorrecta:calificar()
    RespuestaCorrecta --> Selecion: Valor
    Selecion -> Jugador: modificarPuntaje(Valor)
    end
    end

@enduml